name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy static files to GitHub Pages
        run: |
          # Navigate to the directory containing your web build
         

          # Inject the secret into secrets.js
          echo "window._env_ = { GOOGLE_CLOUD_SERVICE_ACCOUNT: '${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}' };" > secrets.js

          # Deploy to GitHub Pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force --quiet "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages

    env:
      GOOGLE_CLOUD_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
